board_qna/urls.py
from django.urls import path

from .views import *

app_name = 'board_qna'

urlpatterns = [
    path('', base.index, name='index'),  # name parameter is to set name of url variable for template
    path('<int:question_id>/', base.detail, name='detail'),  # url for listing board_qna
    path('question/create/', question.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question.question_vote, name='question_vote'),
    path('answer/create/<int:question_id>/', answer.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer.answer_vote, name='answer_vote'),
]

common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.user_signup, name='signup'),
    path('user_drop/', views.user_drop, name='user_drop'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [  # include() is a function for including url file in each app
    path('admin/', admin.site.urls),
    path(route='', view=include('homepage.urls')),
    path(route='board_qna/', view=include('board_qna.urls')),  # mapping URL and view
    path(route='common/', view=include('common.urls')),
]

board_qna/views/base.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator

from board_qna.models import Question


def index(request):
    """index view for question_list"""

    page = request.GET.get(key='page', default='1')  # get value of 'page' from HTTP Request
    question_list = Question.objects.order_by('-id')  # order by id desc
    paginator = Paginator(object_list=question_list, per_page=10)  # number of object per page
    page_obj = paginator.get_page(number=page)  # page to return
    total_pages = paginator.num_pages  # get number of total pages
    context = {'question_list': page_obj, 'total_pages': total_pages}  # total_page is for template filter
    return render(request=request, template_name='board_qna/question_list.html', context=context)


def detail(request, question_id):
    """view for details of each question"""

    question = get_object_or_404(Question, pk=question_id)  # returns 404 instead of 500 when requested not existing question_id
    context = {'question': question}
    return render(request, 'board_qna/question_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- board_qna CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, World!</title>
  </head>
  <body>
  <!-- nav bar -->
  {% include "navbar.html" %}
  <!-- content start -->
  {% block content %}
  {% endblock %}
  <!-- content end -->
  <!-- Bootstrap JS -->
  <script src="{% static 'bootstrap.min.js' %}"></script>
  <!-- JS start -->
  {% block script %}
  {% endblock %}
  <!-- JS end -->
  </body>
</html>

templates/form_errors.html
<!-- alert field/non-field error -->
{% if form.errors %}
<div class="alert alert-danger">
  {% for field in form %}
    <!-- field error -->
    {% if field.errors %}
      <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
      </div>
    {% endif %}
  {% endfor %}
  <!-- non-field error -->
  {% for error in form.non_field_errors %}
    <div>
      <strong>{{ error }}</strong>
    </div>
  {% endfor %}
</div>
{% endif %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Hello World!</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'board_qna:index' %}">Q&A</a>
        </li>
        <li class="nav-item">
          {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'common:logout' %}">로그아웃</a>
          {% else %}
            <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
          {% endif %}
        </li>
        <li class="nav-item">
          {% if not user.is_authenticated %}
            <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
          {% else %}
            <a class="nav-link" href="{% url 'common:user_drop' %}">회원탈퇴({{ user.username }})</a>
          {% endif %}
        </li>
      </ul>
    </div>
  </div>
</nav>