board_qna/urls.py
from django.urls import path

from .views import *

app_name = 'board_qna'

urlpatterns = [
    path('', base.index, name='index'),  # name parameter is to set name of url variable for template
    path('<int:question_id>/', base.detail, name='detail'),  # url for listing board_qna
    path('question/create/', question.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question.question_vote, name='question_vote'),
    path('answer/create/<int:question_id>/', answer.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer.answer_vote, name='answer_vote'),
]

common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.user_signup, name='signup'),
    path('user_drop/', views.user_drop, name='user_drop'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [  # include() is a function for including url file in each app
    path('admin/', admin.site.urls),
    path(route='', view=include('homepage.urls')),
    path(route='board_qna/', view=include('board_qna.urls')),  # mapping URL and view
    path(route='common/', view=include('common.urls')),
]

board_qna/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Question(models.Model):
    """model for question"""

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='question_user')
    subject = models.CharField(max_length=200)
    content = models.TextField()
    date_create = models.DateTimeField()
    date_modify = models.DateTimeField(null=True, blank=True)  # null is for DB, blank is for validation
    voter = models.ManyToManyField(User, related_name='question_voter')

    def __str__(self):
        return self.subject


class Answer(models.Model):
    """model for answer"""

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='answer_user')
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='question_answers')
    content = models.TextField()
    date_create = models.DateTimeField()
    date_modify = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='answer_voter')

    def __str__(self):
        return self.content

board_qna/forms.py
from django import forms
from .models import Question, Answer


class QuestionForm(forms.ModelForm):
    """form for create question"""

    class Meta:
        """class for set metadata to question model"""

        model = Question  # model to use
        fields = ['subject', 'content']  # field for QuestionForm from Question model
        labels = {
            'subject': '제목',
            'content': '내용'
        }


class AnswerForm(forms.ModelForm):
    """form for create answer"""

    class Meta:
        """class for set metadata to answer model"""

        model = Answer
        fields = ['content']
        labels = {
            'content': '답변 내용',
        }

board_qna/views/answer.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from board_qna.models import Question, Answer
from board_qna.forms import AnswerForm


@login_required()
def answer_create(request, question_id):
    """view for create answer"""

    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)  # temporal saving with commit=False option
            answer.user = request.user  # 'request.user' returns current login user
            answer.date_create = timezone.now()  # add time data to form
            answer.question = question
            answer.save()
            question_url = resolve_url('board_qna:detail', question_id=question.id)  # type: ignore
            return redirect(f'{question_url}#answer_{answer.id}')
    else:
        form = AnswerForm()
    context = {'question': question, 'form': form}
    return render(request, 'board_qna/question_detail.html', context)


@login_required()
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.user:
        messages.error(request, '수정 권한이 없습니다')
        return redirect('board_qna:detail', question_id=answer.question.id)  # type: ignore
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.date_modify = timezone.now()
            answer.save()
            question_url = resolve_url('board_qna:detail', question_id=answer.question.id)
            return redirect(f'{question_url}#answer_{answer.id}')
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'board_qna/answer_form.html', context)


@login_required()
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.user:
        messages.error(request, '삭제 권한이 없습니다')
    else:
        answer.delete()
    return redirect('board_qna:detail', question_id=answer.question.id)  # type: ignore


@login_required()
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.user:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    else:
        answer.voter.add(request.user)
    question_url = resolve_url('board_qna:detail', question_id=answer.question.id)  # type: ignore
    return redirect(f'{question_url}#answer_{answer.id}')  # type: ignore

board_qna/views/base.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator

from board_qna.models import Question


def index(request):
    """index view for question_list"""

    page = request.GET.get(key='page', default='1')  # get value of 'page' from HTTP Request
    question_list = Question.objects.order_by('-id')  # order by id desc
    paginator = Paginator(object_list=question_list, per_page=10)  # number of object per page
    page_obj = paginator.get_page(number=page)  # page to return
    total_pages = paginator.num_pages  # get number of total pages
    context = {'question_list': page_obj, 'total_pages': total_pages}  # total_page is for template filter
    return render(request=request, template_name='board_qna/question_list.html', context=context)


def detail(request, question_id):
    """view for details of each question"""

    question = get_object_or_404(Question, pk=question_id)  # returns 404 instead of 500 when requested not existing question_id
    context = {'question': question}
    return render(request, 'board_qna/question_detail.html', context)

board_qna/views/question.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from board_qna.models import Question
from board_qna.forms import QuestionForm


@login_required()
def question_create(request):
    """view for create question"""

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)  # temporal saving with commit=False option
            question.user = request.user  # 'request.user' returns current login user
            question.date_create = timezone.now()  # add time data to form
            question.save()
            return redirect('board_qna:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'board_qna/question_form.html', context)


@login_required()
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.user:  # blocking invalid approach
        messages.error(request, '수정 권한이 없습니다')
        return redirect('board_qna:detail', question_id=question.id)  # type: ignore
    if request.method == "POST":
        form = QuestionForm(data=request.POST, instance=question)  # override instance with requested POST
        if form.is_valid():
            question = form.save(commit=False)
            question.date_modify = timezone.now()  # add current time to form
            question.save()
            return redirect('board_qna:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)  # fill form with current context
    context = {'form': form}
    return render(request, 'board_qna/question_form.html', context)


@login_required()
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.user:
        messages.error(request, '삭제 권한이 없습니다')
        return redirect('board_qna:detail', question_id=question.id)  # type: ignore
    question.delete()
    return redirect('board_qna:index')


@login_required()
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.user:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다')
    else:
        question.voter.add(request.user)
    return redirect('board_qna:detail', question_id=question.id)  # type: ignore

templates/board_qna/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- modify answer -->
<div class="container my-3">
  <form method="POST">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="mb-3">
      <label for="content" class="form-label">답변 내용</label>
      <textarea
        class="form-control"
        name="content"
        id="content"
        rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장 하기</button>
  </form>
</div>
{% endblock %}

templates/board_qna/question_detail.html
{% extends 'base.html' %}
{% block content %}
  <div class="container my-3">
    <!-- message for invalid approach -->
    {% if messages %}
      <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
          <strong>{{ message.tags }}</strong>
          <ul><li>{{ message.message }}</li></ul>
        {% endfor %}
      </div>
    {% endif %}
    <!-- question -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
        <div class="d-flex justify-content-end">
          <div class="badge bg-light text-dark p-2 text-start">
            <div class="mb-2">작성자: {{ question.user.username }}</div>
            <div class="mb-2">작성일: {{ question.date_create|date:'Y-m-d H:i:s' }}</div>
            {% if question.date_modify %}
              <div class="mb-2">수정일: {{ question.date_modify|date:'Y-m-d H:i:s' }}</div>
            {% endif %}
          </div>
        </div>
        <div class="my-3">
          <button
            class="recommend btn btn-sm btn-outline-secondary"
            data-uri="{% url 'board_qna:question_vote' question.id %}">추천
            <span class="badge rounded-pill bg-success">{{ question.voter.count }}</span>
          </button>
          {% if request.user == question.user %}
            <a
              href="{% url 'board_qna:question_modify' question.id %}"
              class="btn btn-sm btn-outline-secondary">수정</a>
            <button
              class="delete btn btn-sm btn-outline-secondary"
              data-uri="{% url 'board_qna:question_delete' question.id %}">삭제</button>
          {% endif %}
        </div>
      </div>
    </div>
    <!-- answer -->
    <h5 class="border-bottom my-3 py-2">{{ question.question_answers.count }}개의 답변이 있습니다.</h5>
    {% for answer in question.question_answers.all %}
      <a id="answer_{{ answer.id }}"></a>
      <div class="card my-3">
        <div class="card-body">
          <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
          <div class="d-flex justify-content-end">
            <div class="badge bg-light text-dark p-2 text-start">
              <div class="mb-2">작성자: {{ answer.user.username }}</div>
              <div class="mb-2">작성일: {{ answer.date_create|date:'Y-m-d H:i:s' }}</div>
              {% if answer.date_modify %}
                <div class="mb-2">수정일: {{ answer.date_modify|date:'Y-m-d H:i:s' }}</div>
              {% endif %}
            </div>
          </div>
          <div class="my-3">
            <button
              class="recommend btn btn-sm btn-outline-secondary"
              data-uri="{% url 'board_qna:answer_vote' answer.id %}">추천
              <span class="badge rounded-pill bg-success">{{ answer.voter.count }}</span>
            </button>
            {% if request.user == answer.user %}
            <a
              href="{% url 'board_qna:answer_modify' answer.id %}"
              class="btn btn-sm btn-outline-secondary">수정</a>
            <button
              class="delete btn btn-sm btn-outline-secondary"
              data-uri="{% url 'board_qna:answer_delete' answer.id %}">삭제</button>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}
    <!-- answer create -->
    <form action="{% url 'board_qna:answer_create' question.id %}" method="POST" class="my-3">
      {% csrf_token %}
      {% include "form_errors.html" %}
      <div class="mb-3">
        <label for="content" class="form-label">답변 내용</label>
        <textarea
          {% if not user.is_authenticated %} disabled {% endif %}
          name="content"
          id="content"
          class="form-control"
          rows="10"></textarea>
      </div>
      <input type="submit" value="답변 등록" class="btn btn-primary">
    </form>
  </div>
{% endblock %}
{% block script %}
  {% load static %}
  <script type="text/javascript" src="{% static 'delete.js' %}"></script>
  <script type="text/javascript" src="{% static 'recommend.js' %}"></script>
{% endblock %}

templates/board_qna/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
  <form method="POST">
    {% csrf_token %}
    {% include "form_errors.html" %}
    <div class="mb-3">
      <label for="subject" class="form-label">제목</label>
      <input
        type="text"
        class="form-control"
        name="subject"
        id="subject"
        value="{{ form.subject.value|default_if_none:'' }}">
    </div>
    <div class="mb-3">
      <label for="content" class="form-label">내용</label>
      <textarea
        class="form-control"
        name="content"
        id="content"
        rows="10">{{ form.content.value|default_if_none:'' }}
      </textarea>
    </div>
    <button type="submit" class="btn btn-primary">저장 하기</button>
  </form>
</div>
{% endblock %}

templates/board_qna/question_list.html
{% extends 'base.html' %}
{% load board_qna_filter %}
{% block content %}
<div class="container my-3 text-nowrap">
  <table class="table">
    <thead>
    <tr class="table-dark text-center" >
      <th>번호</th>
      <th>작성자</th>
      <th>제목</th>
      <th>작성일시</th>
    </tr>
    </thead>
    <tbody>
    {% if question_list %}
      {% for question in question_list %}
        <tr>
          <td class="text-center">{{ question.id }}</td>
          <td class="text-center">{{ question.user }}</td>
          <td width="70%">
            <a href="{% url 'board_qna:detail' question.id %}">{{ question.subject }}</a>
            {% if question.answer_set.count > 0 %}
              <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
            {% endif %}
          </td>
          <td class="text-center" width="5%">{{ question.date_create|date:'Y-m-d H:i:s' }}</td>
        </tr>
      {% endfor %}
    {% else %}
      <tr>
        <td colspan="3">질문이 없습니다.</td>
      </tr>
    {% endif %}
    </tbody>
  </table>
  <!-- paging start -->
  <ul class="pagination justify-content-center">
    <!-- to first page -->
    {% if question_list.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ question_list. }}">처음</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">처음</a>
      </li>
    {% endif %}
    <!-- to prev page -->
    {% if question_list.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
      </li>
    {% endif %}
    <!-- ellipsis -->
    {% if question_list.number > 6 %}
      <li class="page-item page-link disabled">...</li>
    {% endif %}
    <!-- paging list -->
    {% for page_number in question_list.paginator.page_range %}
      {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
          <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
          </li>
        {% endif %}
      {% endif %}
    {% endfor %}
    <!-- ellipsis -->
    {% if total_pages|sub:question_list.number > 5 %}
      <li class="page-item page-link disabled">...</li>
    {% endif %}
    <!-- to next page -->
    {% if question_list.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
      </li>
    {% endif %}
    <!-- to last page -->
    {% if question_list.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ total_pages }}">마지막</a>
      </li>
    {% else %}
      <li class="page-item disabled">
        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">마지막</a>
      </li>
    {% endif %}
  </ul>
  <!-- paging end -->
  <a href="{% url 'board_qna:question_create' %}" class="btn btn-primary">질문 등록</a>
</div>
{% endblock %}